services:
  - type: web
    name: iboard-capture
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
